# Generated by Django 3.2.8 on 2024-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('occupied', 'occupied'), ('unknown', 'unknown')], default='unknown', max_length=20)),
                ('type', models.CharField(choices=[('room', 'room')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='authuser',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
